<Howtorepwd_pg>:
	name: 'howtorepwd'
	RelativeLayout:
		canvas:
			Color:
				rgba: howtorepwd_color
			Rectangle:
				size: self.size
				pos: self.pos
		Label:
			pos_hint: {'center_x':.5, 'center_y':.88}
			markup: True
			text: "忘記密碼"
			font_size: 55
			font_name: font_bold
			color: btn_upperleft
			
		Label:
			pos_hint: {'center_x':.5, 'center_y':.8}
			markup: True
			text: "    選擇哪些聯繫方式應該，我們用來重置您的密碼："
			font_size: 22
			font_name: font_regular
			color: btn_upperleft
		
			



